### ISSUE TITLE
Debug level logging annoying

### ISSUE THREAD

**Issue by soypat** [d2r2/go-bsbmp#8]
Can logger be set manually? Seems like you left it at logger.DebugLevel. Prints out a LOT of stuff I don't need.

see `logger.go`

**Comment by d2r2** [comment]
@soypat, I understand you, and I think you have few approaches:
1) You right with logger.DebugLevel, you can find in example file code how to suppress logging to low level in the beginning of your program:
```go
	lg.Notify("***************************************************************************************************")
	lg.Notify("*** You can change verbosity of output, to modify logging level of modules \"i2c\", \"bsbmp\"")
	lg.Notify("*** Uncomment/comment corresponding lines with call to ChangePackageLogLevel(...)")
	lg.Notify("***************************************************************************************************")
	// Uncomment/comment next lines to suppress/increase verbosity of output
	logger.ChangePackageLogLevel("i2c", logger.InfoLevel)
	logger.ChangePackageLogLevel("bsbmp", logger.InfoLevel)
```
By default highest level of verbosity enabled in file `logger.go` for "bsbmp" package by this code:
```go
// You can manage verbosity of log output
// in the package by changing last parameter value.
var lg = logger.NewPackageLogger("bsbmp",
	logger.DebugLevel,
	// logger.InfoLevel,
)
```
2) You can fork my code and rewrite some part of codes (some people do) to remove my logger and use for instance popular https://github.com/sirupsen/logrus.

Honestly, I choose high level of verbosity, because I think it will be interesting for education purpose to see all DSP happens between host system and sensor.

I think you can start from 1) and if you still feel uncomfortable move further with 2) approach.

If you still have something to discuss, let me know. Success in your studies and research!

**Comment by soypat** [comment]
Thanks! What you say sounds reasonable. I'll close this one
